---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Patwa23/spring-cloudconfig
          searchPaths:
            - 'app*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/Patwa23/spring-cloudconfig-perf
              searchPaths:
                - 'app*'
  security:
    user:
      name: user
      password: password
security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG